# Node parameters
node_frequency: 5.0

# Particle filter param
number_of_particles: 1000
zhit: 10
zrand: 1
sigma_squared: 10
motion_model_noise: [0.01, 0.01, 0.4, 0.008]

# Robot parameters
x_sensor: 0
y_sensor: 0

# Turn plotting on/off
plt_on: 1

# Modes of plotting: 
# 0 - Debug (odometry, laser, likelihood field) 
# 1 - Results (our implementation x amcl) 
plt_mode: 1
