node_frequency: 1.0
# map_roi_xmin: 900
# map_roi_xmax: 1500
# map_roi_ymin: 680
# map_roi_ymax: 1300
initializing_roi_xmin: 0
initializing_roi_xmax: 0
initializing_roi_xmin: 0
initializing_roi_xmin: 0
zhit: 0.8
zrand: 0.2
x_sensor: 0
y_sensor: 0
sigma_squared: 10